### ISSUE TITLE
项目编译不通过

### ISSUE THREAD

**Issue by bg193** [redpanda3/soDLA#17]
拉了master下来，有merge的冲突无法编译通过。
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.json4s:json4s-core_2.12:3.6.1 is selected over 3.5.3
[warn] 	    +- org.json4s:json4s-jackson_2.12:3.6.1               (depends on 3.6.1)
[warn] 	    +- org.json4s:json4s-native_2.12:3.5.3                (depends on 3.5.3)
[warn] 	* org.json4s:json4s-scalap_2.12:3.6.1 is selected over 3.5.3
[warn] 	    +- org.json4s:json4s-core_2.12:3.6.1                  (depends on 3.6.1)
[warn] 	    +- org.json4s:json4s-core_2.12:3.5.3                  (depends on 3.5.3)
[warn] 	* org.json4s:json4s-ast_2.12:3.6.1 is selected over 3.5.3
[warn] 	    +- org.json4s:json4s-core_2.12:3.6.1                  (depends on 3.6.1)
[warn] 	    +- org.json4s:json4s-core_2.12:3.5.3                  (depends on 3.5.3)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 241 Scala sources to /home/bg193/works/soDLA/target/scala-2.12/classes ...
[error] /home/bg193/works/soDLA/src/main/scala/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_CTRL_unit.scala:319:9: Invalid literal number
[error] >>>>>>> 430c4514aba210f9e7c2ff2bb9e32b618a1bb3f6
[error]         ^
[error] /home/bg193/works/soDLA/src/main/scala/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_ctrl.scala:57:9: Invalid literal number
[error] >>>>>>> 430c4514aba210f9e7c2ff2bb9e32b618a1bb3f6
[error]         ^
[error] /home/bg193/works/soDLA/src/main/scala/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_ctrl.scala:85:9: Invalid literal number
[error] >>>>>>> 430c4514aba210f9e7c2ff2bb9e32b618a1bb3f6
[error]         ^
[error] /home/bg193/works/soDLA/src/main/scala/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_ctrl.scala:63:5: illegal start of simple expression
[error]     for(i <- 0 to (conf.NVDLA_CDP_THROUGHPUT - 1)){
[error]     ^
[error] four errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 13 s, completed Jul 25, 2019 3:49:56 PM

另外选择revert-12-master分支也没法编译通过。
 [120] nvdla.NV_NVDLA_glbDriver
 [121] nvdla.NV_NVDLA_partition_aDriver
 [122] nvdla.NV_NVDLA_partition_cDriver
 [123] nvdla.NV_NVDLA_partition_mDriver
 [124] nvdla.NV_NVDLA_partition_pDriver
 [125] nvdla.NV_NVDLA_sdpDriver

Enter number: [info] Packaging /home/bg193/works/soDLA/target/scala-2.12/sodla_2.12-3.2-SNAPSHOT.jar ...
[info] Done packaging.

Invalid number: java.lang.NumberFormatException: For input string: ""
[error] java.lang.RuntimeException: No main class detected.
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$4(Defaults.scala:1163)
[error] 	at scala.Option.getOrElse(Option.scala:121)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$3(Defaults.scala:1163)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (Compile / bgRun) No main class detected.
[error] Total time: 568 s, completed Jul 25, 2019 3:44:30 PM

**Comment by redpanda3** [comment]
现在应该没问题了。

**Comment by bg193** [comment]
看过您在B站上介绍soDLA的视频，不过没有声音，所以也没get到什么点。请问soDLA现在处于什么状态？能上fpga跑了么？

**Comment by redpanda3** [comment]
a, c, m, p部分是可以生成的，但是还没有验证。如果你有fpga的话，可以先试一下。

**Comment by bg193** [comment]
请问这些您是按照nvdla的vmod重写的么？vmod的可读性很差啊

**Comment by redpanda3** [comment]
这是一个performance和敏捷开发性的取舍问题。
如果完全采用敏捷开发，做成一个简单如玩具一样的模块，那样的话，就没有太多的价值了。如何不影响性能的前提下，使其变得“敏捷”，并且可以在此基础之上可以进行二次开发，这是我要做的。
这个项目，如果有更多可以改进的地方，我想可以从以下几个方面入手：
1. 写一个python的脚本，用来生成nvidia的fifo和arbitrator，代替其内部的ness。
2. 根据其sdp或cdp，重新设计一个加速模块，用来加速一些新的算法。

**Comment by bg193** [comment]
弱弱的问句，ness是什么？

**Comment by redpanda3** [comment]
ness最早出现在nvdla在release第一版本nvdla1的rtl的注释，它是nvidia内部的工具，用来生成一些常用的模块 (https://github.com/nvdla/hw/issues/1) 。

**Comment by bg193** [comment]
了解，谢谢！
