### ISSUE TITLE
cannot resolve     "updt_entry_slices_if" in NV_NVDLA_CSC.scala

### ISSUE THREAD

**Issue by lznnnnn1998** [redpanda3/soDLA#59]
Error:(21, 44) not found: type updt_entry_slices_if
        val sc2cdma_dat_updt = ValidIO(new updt_entry_slices_if)
/home/cristinazn/Downloads/soDLA/src/main/scala/nvdla/csc/NV_NVDLA_csc.scala

**Comment by redpanda3** [comment]
Yes, I add defined updt_entry_slices_if into /spec/odif.scala, corresponding to https://github.com/nvdla/hw/tree/master/spec/odif.
