### ISSUE TITLE
not found module NV_NVDLA_SDP_HLS_prelu

### ISSUE THREAD

**Issue by lznnnnn1998** [redpanda3/soDLA#61]
[error] /home/cristinazn/Downloads/soDLA/src/main/scala/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_mul.scala:64:34: not found: type NV_NVDLA_SDP_HLS_prelu
[error]     val x_mul_prelu = Module{new NV_NVDLA_SDP_HLS_prelu(33, 49, 16)}
[error]                                  ^
[error] /home/cristinazn/Downloads/soDLA/src/main/scala/nvdla/sdp/NV_NVDLA_SDP_HLS_Y_int_mul.scala:62:34: not found: type NV_NVDLA_SDP_HLS_prelu
[error]     val x_mul_prelu = Module{new NV_NVDLA_SDP_HLS_prelu}
[error]                                  ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 20 s, completed Oct 3, 2019 9:31:30 PM

**Comment by redpanda3** [comment]
Hi, have you updated all the contents in slibs? I can compile it.

**Comment by lznnnnn1998** [comment]
hi, i have updated all the contents, and got other errors....
[info] Loading project definition from /home/cristinazn/Documents/soDLA/project
[info] Loading settings for project sodla from build.sbt ...
[info] Set current project to sodla (in build file:/home/cristinazn/Documents/soDLA/)
[info] Compiling 236 Scala sources to /home/cristinazn/Documents/soDLA/target/scala-2.12/classes ...
[error] /home/cristinazn/Documents/soDLA/src/main/scala/nvdla/sdp/NV_NVDLA_sdp.scala:35:156: ')' expected but 'else' found.
[error]         val cvif2sdp_n_rd_rsp_pd = if(conf.NVDLA_SECONDARY_MEMIF_ENABLE&conf.NVDLA_SDP_BS_ENABLE) Some(Flipped(DecoupledIO(UInt(conf.NVDLA_DMA_RD_RSP.W))) else None 
[error]                                                                                                                                                            ^
[error] /home/cristinazn/Documents/soDLA/src/main/scala/nvdla/sdp/NV_NVDLA_sdp.scala:37:113: ';' expected but ')' found.
[error]         val sdp_e2mcif_rd_req_pd = if(conf.NVDLA_SDP_BS_ENABLE) Some(DecoupledIO(UInt(conf.NVDLA_DMA_RD_REQ.W)))) else None
[error]                                                                                                                 ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 3 s, completed Oct 4, 2019 4:04:10 PM

**Comment by redpanda3** [comment]
I just finished updating all the sdp with bundle. Please have a check now,

**Comment by lznnnnn1998** [comment]
OK, this problem was solved, but another problem found.
[info] Loading project definition from /home/cristinazn/Downloads/soDLA/project
[info] Loading settings for project sodla from build.sbt ...
[info] Set current project to sodla (in build file:/home/cristinazn/Downloads/soDLA/)
[info] Compiling 236 Scala sources to /home/cristinazn/Downloads/soDLA/target/scala-2.12/classes ...
[error] /home/cristinazn/Downloads/soDLA/src/main/scala/nvdla/nocif/NV_NVDLA_MCIF_READ_IG_arb.scala:65:37: not found: type read_ig_arb
[error]      val u_read_ig_arb = Module(new read_ig_arb)
[error]                                     ^
[error] /home/cristinazn/Downloads/soDLA/src/main/scala/nvdla/nocif/NV_NVDLA_MCIF_READ_IG_arb.scala:98:9: value arb2spt_req_valid is not a member of chisel3.Bundle{val nvdla_core_clk: chisel3.core.Clock; val nvdla_core_rstn: chisel3.core.Bool; val bpt2arb_req_pd: chisel3.core.Vec[chisel3.util.DecoupledIO[chisel3.core.UInt]]; val arb2spt_req_pd: chisel3.util.DecoupledIO[chisel3.core.UInt]; val reg2dp_rd_weight: chisel3.core.Vec[chisel3.core.UInt]}
[error]      io.arb2spt_req_valid := pipe_out.io.vo
[error]         ^
[error] /home/cristinazn/Downloads/soDLA/src/main/scala/nvdla/nocif/NV_NVDLA_MCIF_READ_IG_arb.scala:99:27: value arb2spt_req_ready is not a member of chisel3.Bundle{val nvdla_core_clk: chisel3.core.Clock; val nvdla_core_rstn: chisel3.core.Bool; val bpt2arb_req_pd: chisel3.core.Vec[chisel3.util.DecoupledIO[chisel3.core.UInt]]; val arb2spt_req_pd: chisel3.util.DecoupledIO[chisel3.core.UInt]; val reg2dp_rd_weight: chisel3.core.Vec[chisel3.core.UInt]}
[error]      pipe_out.io.ri := io.arb2spt_req_ready
[error]                           ^
[error] three errors found
[error] (Compile / compileIncremental) Compilation failed

**Comment by redpanda3** [comment]
NOCIF is not finished yet. I will finish them by the end of this month.

**Comment by lznnnnn1998** [comment]
that's a great work~ 
here is a question, how to test the file one by one,  when i use the Launcher, it always compiled all files.
sbt:sodla> test:runMain nvdla.cmac.Launcher  NV_NVDLA_CMAC_CORE_mac
[info] Compiling 236 Scala sources to /home/cristinazn/Downloads/soDLA/target/scala-2.12/classes ...
[error] /home/cristinazn/Downloads/soDLA/src/main/scala/nvdla/nocif/NV_NVDLA_MCIF_READ_IG_arb.scala:66:37: not found: type read_ig_arb
[error]      val u_read_ig_arb = Module(new read_ig_arb(0, io.w ))
[error]                                     ^
[error] /home/cristinazn/Downloads/soDLA/src/main/scala/nvdla/nocif/NV_NVDLA_MCIF_READ_IG_arb.scala:66:55: value w is not a member of chisel3.Bundle{val nvdla_core_clk: chisel3.core.Clock; val nvdla_core_rstn: chisel3.core.Bool; val bpt2arb_req_pd: chisel3.core.Vec[chisel3.util.DecoupledIO[chisel3.core.UInt]]; val arb2spt_req_pd: chisel3.util.DecoupledIO[chisel3.core.UInt]; val reg2dp_rd_weight: chisel3.core.Vec[chisel3.core.UInt]}
[error]      val u_read_ig_arb = Module(new read_ig_arb(0, io.w ))

**Comment by redpanda3** [comment]
Yes, you don't have to use the launcher. These days, I was busy with the pdp, cdp and xxif. Sorry for the late reply.
