### ISSUE TITLE
errors in NV_NVDLA_CMAC_CORE_macTests

### ISSUE THREAD

**Issue by lznnnnn1998** [redpanda3/soDLA#62]
test:runMain nvdla.Launcher NV_NVDLA_CMAC_CORE_mac
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] running nvdla.Launcher NV_NVDLA_CMAC_CORE_mac
Starting tutorial NV_NVDLA_CMAC_CORE_mac
[info] [0.001] Elaborating design...
[info] [1.290] Done elaborating.
Total FIRRTL Compile Time: 1149.8 ms
Total FIRRTL Compile Time: 404.2 ms
file loaded in 0.584299843 seconds, 976 symbols, 583 statements
[info] [0.002] SEED 1570968498148
[info] [0.041] EXPECT AT 24   io_mac_out_bits got 4187531 expected -6773 FAIL
[info] [0.048] EXPECT AT 30   io_mac_out_bits got 4193375 expected -929 FAIL
[info] [0.068] EXPECT AT 66   io_mac_out_bits got 4189920 expected -4384 FAIL
[info] [0.094] EXPECT AT 111   io_mac_out_bits got 4191779 expected -2525 FAIL
[info] [0.103] EXPECT AT 129   io_mac_out_bits got 4191446 expected -2858 FAIL
[info] [0.115] EXPECT AT 168   io_mac_out_bits got 4193353 expected -951 FAIL
[info] [0.129] EXPECT AT 210   io_mac_out_bits got 4190579 expected -3725 FAIL
[info] [0.134] EXPECT AT 243   io_mac_out_bits got 4190421 expected -3883 FAIL
[info] [0.137] EXPECT AT 252   io_mac_out_bits got 4192130 expected -2174 FAIL
[info] [0.140] EXPECT AT 258   io_mac_out_bits got 4192916 expected -1388 FAIL
[info] [0.144] EXPECT AT 270   io_mac_out_bits got 4190181 expected -4123 FAIL
[info] [0.153] EXPECT AT 297   io_mac_out_bits got 4193263 expected -1041 FAIL
[info] [0.157] EXPECT AT 318   io_mac_out_bits got 4192413 expected -1891 FAIL
[info] [0.166] EXPECT AT 372   io_mac_out_bits got 4193326 expected -978 FAIL
[info] [0.170] EXPECT AT 384   io_mac_out_bits got 4192732 expected -1572 FAIL
[info] [0.174] EXPECT AT 396   io_mac_out_bits got 4191606 expected -2698 FAIL
[info] [0.179] EXPECT AT 405   io_mac_out_bits got 4193710 expected -594 FAIL
[info] [0.182] EXPECT AT 417   io_mac_out_bits got 4193806 expected -498 FAIL
[info] [0.185] EXPECT AT 426   io_mac_out_bits got 4192577 expected -1727 FAIL
[info] [0.187] EXPECT AT 435   io_mac_out_bits got 4194252 expected -52 FAIL
[info] [0.190] EXPECT AT 456   io_mac_out_bits got 4190827 expected -3477 FAIL
[info] [0.191] EXPECT AT 459   io_mac_out_bits got 4193014 expected -1290 FAIL
[info] [0.203] EXPECT AT 492   io_mac_out_bits got 4189604 expected -4700 FAIL
[info] [0.206] EXPECT AT 501   io_mac_out_bits got 4193061 expected -1243 FAIL
[info] [0.231] EXPECT AT 567   io_mac_out_bits got 4193386 expected -918 FAIL
[info] [0.234] EXPECT AT 573   io_mac_out_bits got 4188469 expected -5835 FAIL
[info] [0.238] EXPECT AT 582   io_mac_out_bits got 4193912 expected -392 FAIL
[info] [0.247] EXPECT AT 612   io_mac_out_bits got 4190168 expected -4136 FAIL
[info] [0.262] EXPECT AT 654   io_mac_out_bits got 4192232 expected -2072 FAIL
[info] [0.268] EXPECT AT 672   io_mac_out_bits got 4191525 expected -2779 FAIL
[info] [0.269] EXPECT AT 675   io_mac_out_bits got 4193978 expected -326 FAIL
[info] [0.297] EXPECT AT 741   io_mac_out_bits got 4189195 expected -5109 FAIL
[info] [0.299] EXPECT AT 747   io_mac_out_bits got 4191734 expected -2570 FAIL
[info] [0.315] EXPECT AT 780   io_mac_out_bits got 4193506 expected -798 FAIL
[info] [0.317] EXPECT AT 786   io_mac_out_bits got 4192674 expected -1630 FAIL
[info] [0.320] EXPECT AT 795   io_mac_out_bits got 4191443 expected -2861 FAIL
[info] [0.321] EXPECT AT 798   io_mac_out_bits got 4190320 expected -3984 FAIL
[info] [0.325] EXPECT AT 822   io_mac_out_bits got 4188863 expected -5441 FAIL
[info] [0.336] EXPECT AT 891   io_mac_out_bits got 4191464 expected -2840 FAIL
[info] [0.338] EXPECT AT 903   io_mac_out_bits got 4189078 expected -5226 FAIL
[info] [0.344] EXPECT AT 939   io_mac_out_bits got 4192568 expected -1736 FAIL
[info] [0.354] EXPECT AT 993   io_mac_out_bits got 4192435 expected -1869 FAIL
[info] [0.357] EXPECT AT 1005   io_mac_out_bits got 4188330 expected -5974 FAIL
[info] [0.359] EXPECT AT 1014   io_mac_out_bits got 4191033 expected -3271 FAIL
[info] [0.360] EXPECT AT 1017   io_mac_out_bits got 4192698 expected -1606 FAIL
[info] [0.362] EXPECT AT 1032   io_mac_out_bits got 4191512 expected -2792 FAIL
[info] [0.363] EXPECT AT 1041   io_mac_out_bits got 4193620 expected -684 FAIL
[info] [0.367] EXPECT AT 1080   io_mac_out_bits got 4192676 expected -1628 FAIL
[info] [0.370] EXPECT AT 1113   io_mac_out_bits got 4193106 expected -1198 FAIL
[info] [0.372] EXPECT AT 1122   io_mac_out_bits got 4192459 expected -1845 FAIL
[info] [0.372] EXPECT AT 1128   io_mac_out_bits got 4193682 expected -622 FAIL
[info] [0.377] EXPECT AT 1161   io_mac_out_bits got 4193769 expected -535 FAIL
[info] [0.380] EXPECT AT 1194   io_mac_out_bits got 4191367 expected -2937 FAIL
[info] [0.382] EXPECT AT 1206   io_mac_out_bits got 4193397 expected -907 FAIL
[info] [0.384] EXPECT AT 1218   io_mac_out_bits got 4194136 expected -168 FAIL
[info] [0.388] EXPECT AT 1233   io_mac_out_bits got 4191934 expected -2370 FAIL
[info] [0.395] EXPECT AT 1251   io_mac_out_bits got 4191817 expected -2487 FAIL
[info] [0.401] EXPECT AT 1284   io_mac_out_bits got 4184984 expected -9320 FAIL
[info] [0.408] EXPECT AT 1338   io_mac_out_bits got 4188824 expected -5480 FAIL
[info] [0.413] EXPECT AT 1371   io_mac_out_bits got 4192246 expected -2058 FAIL
[info] [0.417] EXPECT AT 1392   io_mac_out_bits got 4192423 expected -1881 FAIL
[info] [0.428] EXPECT AT 1419   io_mac_out_bits got 4191858 expected -2446 FAIL
[info] [0.438] EXPECT AT 1464   io_mac_out_bits got 4190528 expected -3776 FAIL
[info] [0.440] EXPECT AT 1470   io_mac_out_bits got 4192345 expected -1959 FAIL
[info] [0.445] EXPECT AT 1494   io_mac_out_bits got 4192221 expected -2083 FAIL
[info] [0.446] EXPECT AT 1497   io_mac_out_bits got 4192935 expected -1369 FAIL
[info] [0.447] EXPECT AT 1503   io_mac_out_bits got 4194182 expected -122 FAIL
[info] [0.449] EXPECT AT 1509   io_mac_out_bits got 4191784 expected -2520 FAIL
[info] [0.451] EXPECT AT 1515   io_mac_out_bits got 4191054 expected -3250 FAIL
[info] [0.462] EXPECT AT 1557   io_mac_out_bits got 4194033 expected -271 FAIL
[info] [0.464] EXPECT AT 1563   io_mac_out_bits got 4193026 expected -1278 FAIL
[info] [0.466] EXPECT AT 1566   io_mac_out_bits got 4192787 expected -1517 FAIL
[info] [0.476] EXPECT AT 1599   io_mac_out_bits got 4191030 expected -3274 FAIL
[info] [0.477] EXPECT AT 1605   io_mac_out_bits got 4192570 expected -1734 FAIL
[info] [0.488] EXPECT AT 1677   io_mac_out_bits got 4194044 expected -260 FAIL
[info] [0.491] EXPECT AT 1692   io_mac_out_bits got 4193138 expected -1166 FAIL
[info] [0.496] EXPECT AT 1731   io_mac_out_bits got 4194054 expected -250 FAIL
[info] [0.498] EXPECT AT 1737   io_mac_out_bits got 4193904 expected -400 FAIL
[info] [0.505] EXPECT AT 1782   io_mac_out_bits got 4194020 expected -284 FAIL
[info] [0.508] EXPECT AT 1803   io_mac_out_bits got 4193178 expected -1126 FAIL
[info] [0.510] EXPECT AT 1833   io_mac_out_bits got 4190310 expected -3994 FAIL
[info] [0.513] EXPECT AT 1863   io_mac_out_bits got 4189283 expected -5021 FAIL
[info] [0.514] EXPECT AT 1875   io_mac_out_bits got 4193182 expected -1122 FAIL
[info] [0.515] EXPECT AT 1878   io_mac_out_bits got 4193737 expected -567 FAIL
[info] [0.522] EXPECT AT 1947   io_mac_out_bits got 4193788 expected -516 FAIL
[info] [0.527] EXPECT AT 1971   io_mac_out_bits got 4192400 expected -1904 FAIL
[info] [0.529] EXPECT AT 1986   io_mac_out_bits got 4193297 expected -1007 FAIL
[info] [0.532] EXPECT AT 2007   io_mac_out_bits got 4189358 expected -4946 FAIL
[info] [0.543] EXPECT AT 2100   io_mac_out_bits got 4192974 expected -1330 FAIL
[info] [0.549] EXPECT AT 2136   io_mac_out_bits got 4194200 expected -104 FAIL
[info] [0.554] EXPECT AT 2175   io_mac_out_bits got 4189499 expected -4805 FAIL
[info] [0.562] EXPECT AT 2220   io_mac_out_bits got 4186483 expected -7821 FAIL
[info] [0.563] EXPECT AT 2223   io_mac_out_bits got 4193524 expected -780 FAIL
[info] [0.566] EXPECT AT 2241   io_mac_out_bits got 4193397 expected -907 FAIL
[info] [0.570] EXPECT AT 2277   io_mac_out_bits got 4192852 expected -1452 FAIL
[info] [0.574] EXPECT AT 2310   io_mac_out_bits got 4194302 expected -2 FAIL
[info] [0.576] EXPECT AT 2325   io_mac_out_bits got 4189081 expected -5223 FAIL
[info] [0.579] EXPECT AT 2343   io_mac_out_bits got 4189800 expected -4504 FAIL
[info] [0.581] EXPECT AT 2355   io_mac_out_bits got 4189405 expected -4899 FAIL
[info] [0.591] EXPECT AT 2433   io_mac_out_bits got 4194098 expected -206 FAIL
[info] [0.592] EXPECT AT 2439   io_mac_out_bits got 4192963 expected -1341 FAIL
[info] [0.593] EXPECT AT 2451   io_mac_out_bits got 4193314 expected -990 FAIL
[info] [0.596] EXPECT AT 2478   io_mac_out_bits got 4194152 expected -152 FAIL
[info] [0.597] EXPECT AT 2484   io_mac_out_bits got 4191987 expected -2317 FAIL
[info] [0.602] EXPECT AT 2535   io_mac_out_bits got 4193210 expected -1094 FAIL
[info] [0.611] EXPECT AT 2610   io_mac_out_bits got 4192478 expected -1826 FAIL
[info] [0.634] EXPECT AT 2820   io_mac_out_bits got 4191447 expected -2857 FAIL
[info] [0.634] EXPECT AT 2823   io_mac_out_bits got 4188765 expected -5539 FAIL
[info] [0.640] EXPECT AT 2859   io_mac_out_bits got 4191718 expected -2586 FAIL
[info] [0.643] EXPECT AT 2874   io_mac_out_bits got 4191738 expected -2566 FAIL
[info] [0.655] EXPECT AT 2949   io_mac_out_bits got 4193408 expected -896 FAIL
[info] [0.657] EXPECT AT 2970   io_mac_out_bits got 4194236 expected -68 FAIL
test NV_NVDLA_CMAC_CORE_mac Success: 378 tests passed in 3005 cycles in 0.692630 seconds 4338.54 Hz
[info] [0.662] RAN 3000 CYCLES FAILED FIRST AT CYCLE 24
================================================================================
Errors: 1: in the following tutorials
Tutorial NV_NVDLA_CMAC_CORE_mac: test error occurred
================================================================================
2019-10-13 20:08:22,455 shutdown-hooks-run-all ERROR No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2

**Comment by redpanda3** [comment]
In the NV_NVDLA_CMAC_CORE_macTests.scala, you can change the wt(i) = rnd.nextInt(2*(1<<(conf.CMAC_BPE-1)-1)) - (1 << (conf.CMAC_BPE-1) - 1) to rnd.nextInt(1 << (conf.CMAC_BPE-1) )  (and also dat(i)) for the moment. However, this module is intended for SInt, so I'm asking more people about this issue.

**Comment by lznnnnn1998** [comment]
thanks, i will try it.

**Comment by redpanda3** [comment]
I've asked Jack Koenig about this issue, this problem comes from the tester, UInt can only receive the non-negative values. I've tried to make SInt type as IO before, however, because it is inconvenient for SInt to store into the buffer, package and unpackage. So I switched them to UInt. The easiest way to test them is to change the computational modules into SInt IO modules, and then test it, or you can just test the non-negative values.
