### ISSUE TITLE
No implicits found for parameter conf: nvdlaConfig in nvdla.cmac.Launcher

### ISSUE THREAD

**Issue by lznnnnn1998** [redpanda3/soDLA#63]
in the cmac Launcher, it used cmacConfiguation,  but those classes in nvdla.cmac used nvdlaConfig. is there something not finished yet?

**Comment by redpanda3** [comment]
You are correct, in the first version, configuration within each tile is separated, however, in the second version, configuration within each tile is connected as nvdlaConfig.

**Comment by redpanda3** [comment]
I will change cmacConfiguation to nvdlaConfig.
